All broken links fixed in computer_science/CONTRIBUTING.md.
shhossain/computer_science pull request #25
Opened 2022-10-01 15:28 UTC by mdfaizanahmed786

All broken links have been fixed.

2022-10-01 15:36 UTC, shhossain requested changes
Change link

2022-10-01 15:36 UTC, shhossain commented on CONTRIBUTING.md
> +To get an overview of the project, read the [README](https://github.com/mdfaizanahmed786/computer_science/blob/contributingmd-links-fix/readme.md). Here are some resources to help you get started wit
Change this link to "/readme.md" .

2022-10-01 15:37 UTC, mdfaizanahmed786 commented on CONTRIBUTING.md
> +To get an overview of the project, read the [README](https://github.com/mdfaizanahmed786/computer_science/blob/contributingmd-links-fix/readme.md). Here are some resources to help you get started wit
I'm sorry, I've actually added my link.

2022-10-01 15:38 UTC, shhossain commented on CONTRIBUTING.md
> +To get an overview of the project, read the [README](https://github.com/mdfaizanahmed786/computer_science/blob/contributingmd-links-fix/readme.md). Here are some resources to help you get started wit
No problem. Just change it and push it.

2022-10-01 15:43 UTC, shhossain requested changes
Just change to /readme.md

2022-10-01 15:48 UTC, mdfaizanahmed786 commented
Hi there, I updated the link.

2022-10-01 15:50 UTC, shhossain commented
Merging...

2022-10-01 15:50 UTC, merged

2022-10-01 15:55 UTC, mdfaizanahmed786 commented
I hope you've liked my work. This was my first open-source contribution. I know to understand it completely I've made some mistakes but I managed to contribute to your repository.

2022-10-01 15:57 UTC, shhossain commented
Congratulations 🎊.

2022-10-01 16:00 UTC, mdfaizanahmed786 commented
Thanks! ❤️

2022-10-03 15:00 UTC, mdfaizanahmed786 commented
> Congratulations 🎊.

> Hey there, can you please mark by PR as hacktober-fest? It would be a great help.

2022-10-03 15:04 UTC, shhossain commented
@mdfaizanahmed786 To get "hactoberfest-accepted" label you need to add info and it must be unique. minimum ➕200 addition.

2022-10-03 15:07 UTC, mdfaizanahmed786 commented
> @mdfaizanahmed786 To get "hactoberfest-accepted" label you need to add info and it must be unique. minimum ➕200 addition.

> If you don't mind, can you describe in detail what info I need to add? Thank you for you time!

2022-10-03 15:08 UTC, shhossain commented
@mdfaizanahmed786 See this [issue](https://github.com/shhossain/computer_science/issues/1)

2022-10-03 15:11 UTC, mdfaizanahmed786 commented
> @mdfaizanahmed786 See this [issue](https://github.com/shhossain/computer_science/issues/1)

> Got it! Thanks!