first commit
shhossain/computer_science pull request #49
Opened 2022-10-02 16:37 UTC by rishiwardhan

hi, just added new lines to the project

2022-10-02 16:40 UTC, rishiwardhan commented
hi, just added new lines to the projects to learners to understand even more better

2022-10-02 16:47 UTC, rishiwardhan commented
please check the lines and merge it .

2022-10-02 16:53 UTC, shhossain requested changes
Please remove the commented lines.

2022-10-02 16:53 UTC, shhossain commented on readme.md
> +### Major functionalities of an OS (operating system)
Remove this

2022-10-02 16:53 UTC, shhossain commented on readme.md
> +If you are not aware of the difference between memory and storage in computers, this article covers the differences between the two. {memory and storage}
Don't need to change

2022-10-02 16:53 UTC, shhossain commented on readme.md
> +The term "memory" refers to the component within your computer that allows for short-term data access. You may recognise this component as DRAM, or dynamic random-access memory. Your computer perform
Italic looks better

2022-10-02 16:53 UTC, shhossain commented on readme.md
> +There are many kinds of file systems, each has unique structures and logic, properties of speed, flexibility, security, size and more. Some file systems have been designed to be used for specific app
Not needed

2022-10-02 16:53 UTC, shhossain commented on readme.md
> +- **Convenience  of os**: An OS makes a computer more convenient to use.
Simple is better

2022-10-02 16:53 UTC, shhossain commented on readme.md
> +- **Efficiency of os**: An OS allows the computer system resources to be used efficiently.
Simple is better. Remove this

2022-10-02 16:53 UTC, shhossain commented on readme.md
> +An operating system (often abbreviated to Os) acts as an intermediary between the user of a computer and computer hardware. The purpose of an operating system is to provide an environment in which an
Unnecessary

2022-10-02 16:56 UTC, shhossain commented
@rishiwardhan you've added lots of unnecessary words or changed to similar words. The issue is about adding something new or fixing typos if spotted. Try to add new things next time.

2022-10-02 17:14 UTC, closed without merging

2022-10-03 15:18 UTC, rishiwardhan commented
Oh , ok then can I add new materials and fix typos

2022-10-03 15:19 UTC, shhossain commented
@rishiwardhan yes you can.

2022-10-03 15:29 UTC, rishiwardhan commented
Ok thank you

2022-10-04 14:06 UTC, rishiwardhan commented
Hi, yesterday I have added about Kerberos