Added more simplified example to OOPS
shhossain/computer_science pull request #697
Opened 2023-10-26 13:03 UTC by aslezar

## Proposed changes

Added more simplified example of BookStore to OOPS section for engineer to understand it easily.

## Types of changes

What types of changes does your content introduce to this project?
_Put an `x` in the boxes that apply (without "`")_

- [ ] Proofreading (fix spelling, grammar, punctuation, accuracy)
- [x] New content (new section, new readme, etc.)
- [ ] Modifications (modifying existing content)
- [ ] Other (please describe)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. Don't hesitate to ask if you're unsure about any of them. We're here to help! This simply reminds us of what we will look for before merging your code._
_Note: If you submit code make sure to test it_

- [x] Tested any code that was added/modified in this PR
- [ ] Added external links
- [ ] Added internal links
- [ ] Added images
- [ ] Added videos
- [x] Added code snippets

### Reviewers: 
- [ ] @username

_Please ensure that you are not adding any sensitive information like API keys, secrets, passwords, tokens, usernames, or other credentials. Refrain from adding your name, email, or other personal information._

2023-10-27 07:50 UTC, shhossain requested changes

2023-10-27 07:50 UTC, shhossain commented on .all-contributorsrc
Don't edit this file.

2023-10-27 09:47 UTC, aslezar commented on .all-contributorsrc
OK, I have reverted that commit.

2023-10-28 14:27 UTC, shhossain approved these changes
No problem.

2023-10-28 14:29 UTC, merged

2023-10-28 14:30 UTC, shhossain commented
@all-contributors add @aslezar for code.