Add CN Translation
shhossain/computer_science pull request #723
Opened 2023-11-08 16:30 UTC by jiangfz1997

## Proposed changes
Add Readme CN translation for Chinese users. Resolve #633

## Types of changes

What types of changes does your content introduce to this project?
_Put an `x` in the boxes that apply (without "`")_

- [ ] Proofreading (fix spelling, grammar, punctuation, accuracy) [Proofreading](https://www.scribbr.com/language-rules/what-is-proofreading/)
- [x] New content (new section, new readme, etc.)
- [x] Modifications (modifying existing content)
- [ ] Other (please describe)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. Don't hesitate to ask if you're unsure about any of them. We're here to help! This simply reminds us of what we will look for before merging your code._
_Note: If you submit code make sure to test it_

- [ ] Tested any code that was added/modified in this PR
- [ ] Added external links
- [ ] Added internal links
- [ ] Added images
- [ ] Added videos
- [ ] Added code snippets

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

## Adding your name to the contributor's list
Comment "@all-contributors please add @your_username for content" to add your name to the contributor's list.
_You can change the "content" with any of [this](https://allcontributors.org/docs/en/emoji-key)_

### Reviewers: 
- [ ] @username

_Please ensure that you are not adding any sensitive information like API keys, secrets, passwords, tokens, usernames, or other credentials. Refrain from adding your name, email, or other personal information._

2023-11-16 15:53 UTC, shhossain requested changes

2023-11-16 15:53 UTC, shhossain commented on README_cn.md
> +- [介绍](#introduction)
You need to fix all of the items' links in the table of contents.
FROM:

\[介绍\]\(\#introduction\)

TO:
\[介绍\](\#介绍\)

Do this for all of the items.

2023-11-25 07:24 UTC, jiangfz1997 commented
Hi @shhossain,
Sorry for the late reply, I just fixed the intro issue now it should be able to redirect to the title for each paragraph.

2023-11-25 15:54 UTC, shhossain approved these changes
@jiangfz1997 No problem. Merging.

2023-11-25 15:54 UTC, merged

2023-11-25 15:55 UTC, shhossain commented
@all-contributors add @jiangfz1997 for content.